# Generated by Django 3.0.8 on 2020-07-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_auto_20200729_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
